package org.wiicompiled.portlab;

import android.os.Bundle;
import android.os.Build;
import android.os.PowerManager;
import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowInsets;
import android.widget.FrameLayout;
import android.widget.TextView;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import org.libsdl.app.SDLActivity;
import org.libsdl.app.SDLSurface;

/** Runs a private, user-built runtime in a separate process to isolate runtime globals. */
public final class GameActivity extends SDLActivity {
    private static final int PAD_LEFT=0x0001, PAD_RIGHT=0x0002, PAD_DOWN=0x0004, PAD_UP=0x0008;
    private static final int PAD_Z=0x0010, PAD_R=0x0020, PAD_L=0x0040;
    private static final int PAD_A=0x0100, PAD_B=0x0200, PAD_X=0x0400, PAD_Y=0x0800, PAD_START=0x1000;
    private int virtualButtons, virtualStickX, virtualStickY;
    private boolean virtualPadInstalled;
    private String runtimeLibrary = CodePatchRegistry.BASE_LIBRARY;
    private RuntimePackManager.Pack runtimePack;
    private File runtimeFile;
    private static native void nativeSetVirtualPadState(int buttons, int stickX, int stickY);

    @Override protected SDLSurface createSDLSurface(Context context) {
        return new AuroraSurface(context);
    }
    @Override protected String[] getLibraries() { return new String[]{runtimeLibrary}; }
    @Override protected String getMainSharedObject() {
        return runtimeFile == null ? super.getMainSharedObject() : runtimeFile.getAbsolutePath();
    }
    @Override protected void onCreate(Bundle state) {
        // SDLActivity loads libraries and starts native work in super.onCreate.
        // Prepare config before allowing that startup path to run.
        try {
            File external = getExternalFilesDir(null);
            if (external == null) throw new java.io.IOException("External app storage unavailable");
            // libWiiCompiled reads config from global constructors. Seed native paths before
            // SDLActivity loads it; SDL's Android JNI context does not exist at that point.
            NativeProbe.configureAndroidPaths(getFilesDir().getAbsolutePath(), external.getAbsolutePath());
            AndroidModManager.prepareEnvironment(this);
            runtimeLibrary = AndroidModManager.runtimeLibrary(this);
            runtimePack = RuntimePackManager.active(this);
            if (runtimePack != null) {
                runtimeFile = RuntimePackManager.prepareForLaunch(this, runtimeLibrary);
                GpuDriverManager.prepareEnvironment(this, runtimeFile.getParentFile().getAbsolutePath());
            } else if (BuildConfig.WITH_GAME) {
                // Compatibility path for old private developer APKs with embedded JNI libraries.
                GpuDriverManager.prepareEnvironment(this);
            } else {
                throw new java.io.IOException("No private ARM64 runtime is installed. Build it on this tablet or import a runtime pack.");
            }
            android.util.Log.i("WiiCompiled", "Selected translated runtime: " + runtimeLibrary);
            File game = new File(external, "game");
            File data = new File(game, "disc");
            if (!new File(data, "sys/main.dol").isFile() || !new File(data, "files/rel/StaticR.rel").isFile())
                throw new java.io.IOException("Game data is missing. Run the local deployment script first.");
            File stateDir = new File(getFilesDir(), "WiiCompiled");
            if (!stateDir.isDirectory() && !stateDir.mkdirs()) throw new java.io.IOException("Cannot create state directory");
            File config = new File(stateDir, "Config.toml");
            if (!config.exists()) {
                // APK-specific path is generated by Android, never interpolated from an imported file.
                String text = "[video]\ngraphics_api = \"vulkan\"\nresolution_multiplier = 1.0\n"
                    + "frame_interpolation_fps = 0\nshow_fps = true\n"
                    + "[network]\nenabled = false\n[discord]\nenabled = false\n"
                    + "[paths]\ndvd_root = \"" + data.getAbsolutePath() + "\"\n";
                try (FileOutputStream output = new FileOutputStream(config)) {
                    output.write(text.getBytes(StandardCharsets.UTF_8));
                }
            }
        } catch (Exception error) {
            android.util.Log.e("WiiCompiled", "Cannot prepare game", error);
            // SDL must still initialize its Activity base, but must not load/start native game code.
            preparationError = error.getMessage();
        }
        super.onCreate(state);
        if (preparationError != null) {
            new android.app.AlertDialog.Builder(this).setTitle("Game data unavailable")
                .setMessage(preparationError).setPositiveButton("Close", (d, w) -> finish()).show();
        } else {
            enableSustainedPerformanceForRetroRewind();
            installTouchControls();
        }
    }
    private String preparationError;

    private void enableSustainedPerformanceForRetroRewind() {
        if (!CodePatchRegistry.RETRO_LIBRARY.equals(runtimeLibrary) || Build.VERSION.SDK_INT < 24) {
            return;
        }
        PowerManager power = getSystemService(PowerManager.class);
        if (power != null && power.isSustainedPerformanceModeSupported()) {
            getWindow().setSustainedPerformanceMode(true);
            android.util.Log.i("WiiCompiled", "Enabled sustained performance mode for Retro Rewind");
        }
    }

    private void installTouchControls() {
        resetVirtualPad();
        virtualPadInstalled = true;
        FrameLayout controls = new FrameLayout(this);
        controls.setClipChildren(false);
        controls.setOnApplyWindowInsetsListener((view, windowInsets) -> {
            android.graphics.Insets insets = windowInsets.getInsets(WindowInsets.Type.systemBars());
            view.setPadding(insets.left, insets.top, insets.right, insets.bottom);
            return windowInsets;
        });
        mLayout.addView(controls, new android.widget.RelativeLayout.LayoutParams(-1, -1));
        controls.requestApplyInsets();
        int edge = dp(24), stickSize = dp(150), dpadSize = dp(42), dpadGap = dp(4);

        AnalogStickView stick = new AnalogStickView(this);
        FrameLayout.LayoutParams stickParams = new FrameLayout.LayoutParams(
            stickSize, stickSize, Gravity.BOTTOM | Gravity.LEFT);
        stickParams.leftMargin = edge;
        stickParams.bottomMargin = edge;
        controls.addView(stick, stickParams);

        int dpadLeft = edge + stickSize + dp(20);
        addPadButton(controls, "◀", PAD_LEFT, Gravity.BOTTOM | Gravity.LEFT,
            dpadLeft, edge + dpadSize + dpadGap, dpadSize, dpadSize);
        addPadButton(controls, "▶", PAD_RIGHT, Gravity.BOTTOM | Gravity.LEFT,
            dpadLeft + (dpadSize + dpadGap) * 2, edge + dpadSize + dpadGap, dpadSize, dpadSize);
        addPadButton(controls, "▲", PAD_UP, Gravity.BOTTOM | Gravity.LEFT,
            dpadLeft + dpadSize + dpadGap, edge + (dpadSize + dpadGap) * 2, dpadSize, dpadSize);
        addPadButton(controls, "▼", PAD_DOWN, Gravity.BOTTOM | Gravity.LEFT,
            dpadLeft + dpadSize + dpadGap, edge, dpadSize, dpadSize);

        addPadButton(controls, "L", PAD_L, Gravity.BOTTOM | Gravity.LEFT,
            edge, edge + stickSize + dp(12), dp(92), dp(44));

        addPadButton(controls, "A", PAD_A, Gravity.BOTTOM | Gravity.RIGHT,
            edge, edge + dp(58), dp(82), dp(82));
        addPadButton(controls, "B", PAD_B, Gravity.BOTTOM | Gravity.RIGHT,
            edge + dp(96), edge, dp(56), dp(56));
        addPadButton(controls, "X", PAD_X, Gravity.BOTTOM | Gravity.RIGHT,
            edge, edge + dp(154), dp(56), dp(56));
        addPadButton(controls, "Y", PAD_Y, Gravity.BOTTOM | Gravity.RIGHT,
            edge + dp(98), edge + dp(132), dp(56), dp(56));
        addPadButton(controls, "R", PAD_R, Gravity.BOTTOM | Gravity.RIGHT,
            edge, edge + dp(224), dp(92), dp(44));
        addPadButton(controls, "Z", PAD_Z, Gravity.BOTTOM | Gravity.RIGHT,
            edge + dp(104), edge + dp(224), dp(68), dp(44));
        addPadButton(controls, "+", PAD_START, Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL,
            0, edge, dp(62), dp(50));
    }

    private void addPadButton(FrameLayout parent, String label, int mask, int gravity,
                              int horizontalMargin, int bottomMargin, int width, int height) {
        TextView button = new TextView(this);
        button.setText(label);
        button.setTextColor(Color.WHITE);
        button.setTextSize(20);
        button.setGravity(Gravity.CENTER);
        button.setAlpha(0.62f);
        button.setContentDescription(label + " button");
        GradientDrawable background = new GradientDrawable();
        background.setColor(Color.argb(165, 15, 23, 42));
        background.setStroke(dp(2), Color.argb(210, 255, 255, 255));
        background.setCornerRadius(height / 2f);
        button.setBackground(background);
        button.setOnTouchListener((view, event) -> {
            boolean down = event.getActionMasked() != MotionEvent.ACTION_UP
                && event.getActionMasked() != MotionEvent.ACTION_CANCEL;
            if (down) virtualButtons |= mask; else virtualButtons &= ~mask;
            publishVirtualPad();
            view.setAlpha(down ? 0.95f : 0.62f);
            return true;
        });
        FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(width, height, gravity);
        if ((gravity & Gravity.LEFT) != 0) params.leftMargin = horizontalMargin;
        if ((gravity & Gravity.RIGHT) != 0) params.rightMargin = horizontalMargin;
        params.bottomMargin = bottomMargin;
        parent.addView(button, params);
    }

    private void publishVirtualPad() {
        nativeSetVirtualPadState(virtualButtons, virtualStickX, virtualStickY);
    }

    private void resetVirtualPad() {
        virtualButtons = virtualStickX = virtualStickY = 0;
        publishVirtualPad();
    }

    private final class AnalogStickView extends View {
        private final Paint baseFill = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final Paint outline = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final Paint knob = new Paint(Paint.ANTI_ALIAS_FLAG);
        private float centerX, centerY, knobX, knobY, radius;
        private int activePointer = -1;

        AnalogStickView(Context context) {
            super(context);
            setContentDescription("Steering stick");
            baseFill.setColor(Color.argb(145, 15, 23, 42));
            outline.setStyle(Paint.Style.STROKE);
            outline.setStrokeWidth(dp(2));
            outline.setColor(Color.argb(210, 255, 255, 255));
            knob.setColor(Color.argb(205, 148, 163, 184));
        }

        @Override protected void onSizeChanged(int width, int height, int oldWidth, int oldHeight) {
            centerX = knobX = width / 2f;
            centerY = knobY = height / 2f;
            radius = Math.min(width, height) / 2f - dp(5);
        }

        @Override protected void onDraw(Canvas canvas) {
            super.onDraw(canvas);
            canvas.drawCircle(centerX, centerY, radius, baseFill);
            canvas.drawCircle(centerX, centerY, radius, outline);
            canvas.drawCircle(knobX, knobY, radius * 0.38f, knob);
        }

        @Override public boolean onTouchEvent(MotionEvent event) {
            int action = event.getActionMasked();
            if (action == MotionEvent.ACTION_DOWN) {
                activePointer = event.getPointerId(0);
                updateStick(event.getX(0), event.getY(0));
                return true;
            }
            if (action == MotionEvent.ACTION_MOVE && activePointer != -1) {
                int index = event.findPointerIndex(activePointer);
                if (index >= 0) updateStick(event.getX(index), event.getY(index));
                return true;
            }
            if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL ||
                (action == MotionEvent.ACTION_POINTER_UP &&
                 event.getPointerId(event.getActionIndex()) == activePointer)) {
                activePointer = -1;
                knobX = centerX;
                knobY = centerY;
                virtualStickX = virtualStickY = 0;
                publishVirtualPad();
                invalidate();
                performClick();
                return true;
            }
            return true;
        }

        private void updateStick(float x, float y) {
            float dx = x - centerX, dy = y - centerY;
            float distance = (float)Math.hypot(dx, dy);
            if (distance > radius && distance > 0f) {
                float scale = radius / distance;
                dx *= scale;
                dy *= scale;
                distance = radius;
            }
            knobX = centerX + dx;
            knobY = centerY + dy;
            float deadZone = radius * 0.12f;
            if (distance <= deadZone) {
                virtualStickX = virtualStickY = 0;
            } else {
                float magnitude = (distance - deadZone) / (radius - deadZone);
                virtualStickX = Math.round((dx / distance) * magnitude * 127f);
                virtualStickY = Math.round((-dy / distance) * magnitude * 127f);
            }
            publishVirtualPad();
            invalidate();
        }

        @Override public boolean performClick() {
            super.performClick();
            return true;
        }
    }

    private int dp(int value) { return Math.round(value * getResources().getDisplayMetrics().density); }

    @Override protected void onPause() {
        if (virtualPadInstalled) resetVirtualPad();
        super.onPause();
    }

    @Override public void loadLibraries() {
        if (preparationError != null) throw new IllegalStateException(preparationError);
        if (runtimePack == null) {
            super.loadLibraries();
            return;
        }
        try { RuntimePackManager.load(runtimePack, runtimeLibrary); }
        catch (java.io.IOException error) { throw new IllegalStateException(error); }
    }
    @Override protected void onDestroy() {
        super.onDestroy();
        // This activity lives in :game; don't leave non-resettable guest globals for another run.
        android.os.Process.killProcess(android.os.Process.myPid());
    }
}

