package org.wiicompiled.portlab;

import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.provider.OpenableColumns;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Locale;
import java.util.Properties;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/** Imports and selects user-provided arm64 Vulkan drivers in app-private storage. */
final class GpuDriverManager {
    private static final String ROOT = "gpu-drivers", ACTIVE = "active.properties";
    private static final String ABI = "arm64-v8a";
    private static final String[] SONAMES = {
        "libvulkan_freedreno.so", "vulkan.freedreno.so", "vulkan.adreno.so", "libvulkan.so"
    };
    private static final int MAX_ENTRIES = 512;
    private static final long MAX_ENTRY_BYTES = 256L * 1024 * 1024;
    private static final long MAX_TOTAL_BYTES = 512L * 1024 * 1024;

    static final class Selection {
        final String label, directory, soname;
        Selection(String label, String directory, String soname) {
            this.label = label; this.directory = directory; this.soname = soname;
        }
    }

    static String status(Context context) {
        Selection selected = load(context);
        if (selected == null) return "System Vulkan driver (default)";
        return "Custom: " + selected.label + "\n" + selected.soname
            + "\nTakes effect the next time the game starts.";
    }

    static String runtimeStatus(Context context) {
        File status = new File(context.getFilesDir(), "gpu-driver-runtime-status.txt");
        if (!status.isFile()) return null;
        try (FileInputStream input = new FileInputStream(status)) {
            byte[] bytes = new byte[8192];
            int total = 0;
            for (int read; total < bytes.length
                    && (read = input.read(bytes, total, bytes.length - total)) != -1;) total += read;
            return new String(bytes, 0, total, java.nio.charset.StandardCharsets.UTF_8).trim();
        } catch (IOException ignored) { return null; }
    }

    static String importZip(Context context, Uri uri) throws IOException {
        String displayName = displayName(context, uri);
        String stem = displayName.replaceFirst("(?i)\\.zip$", "")
            .toLowerCase(Locale.US).replaceAll("[^a-z0-9._-]+", "-")
            .replaceAll("^-+|-+$", "");
        if (stem.isEmpty()) stem = "gpu-driver";
        File root = root(context);
        File destination = new File(new File(root, "imports"), stem + "-" + System.currentTimeMillis());
        if (!destination.mkdirs()) throw new IOException("Cannot create private driver directory");
        try {
            extractSafely(context, uri, destination);
            File driver = findSupportedDriver(destination);
            if (driver == null) throw new IOException("ZIP contains no ARM64 Vulkan driver library. "
                + "Accepted names include libvulkan_freedreno.so, vulkan.adreno.so, and other Vulkan-named .so files.");
            Properties active = new Properties();
            active.setProperty("label", displayName);
            active.setProperty("directory", driver.getParentFile().getCanonicalPath());
            active.setProperty("soname", driver.getName());
            File activeFile = new File(root, ACTIVE), temporary = new File(root, ACTIVE + ".tmp");
            try (OutputStream output = new FileOutputStream(temporary)) {
                active.store(output, "Generated by WiiCompiled Android; user driver is not bundled in the APK");
            }
            if (activeFile.exists() && !activeFile.delete()) throw new IOException("Cannot replace driver selection");
            if (!temporary.renameTo(activeFile)) throw new IOException("Cannot activate imported driver");
            return "Imported and selected " + displayName + ". Start the game to test it.";
        } catch (IOException error) {
            deleteRecursively(destination);
            throw error;
        }
    }

    static void reset(Context context) throws IOException {
        File active = new File(root(context), ACTIVE);
        if (active.exists() && !active.delete()) throw new IOException("Cannot clear custom driver selection");
        new File(context.getFilesDir(), "gpu-driver-runtime-status.txt").delete();
    }

    static void prepareEnvironment(Context context) {
        Selection selection = load(context);
        String directory = selection == null ? null : selection.directory;
        String soname = selection == null ? null : selection.soname;
        String label = selection == null ? null : selection.label;
        NativeProbe.configureCustomVulkanDriver(directory, soname, label,
            context.getApplicationInfo().nativeLibraryDir,
            new File(root(context), "tmp").getAbsolutePath(), context.getFilesDir().getAbsolutePath());
    }

    private static Selection load(Context context) {
        File active = new File(root(context), ACTIVE);
        if (!active.isFile()) return null;
        try (InputStream input = new FileInputStream(active)) {
            Properties values = new Properties(); values.load(input);
            String directory = values.getProperty("directory", "");
            String soname = values.getProperty("soname", "");
            String label = values.getProperty("label", soname);
            File dir = new File(directory), file = new File(dir, soname);
            String imports = new File(root(context), "imports").getCanonicalPath() + File.separator;
            if (!dir.getCanonicalPath().startsWith(imports) || !file.isFile() || !supported(soname)) return null;
            return new Selection(label, dir.getCanonicalPath(), soname);
        } catch (IOException ignored) { return null; }
    }

    private static File root(Context context) {
        File root = new File(context.getFilesDir(), ROOT);
        new File(root, "imports").mkdirs(); new File(root, "tmp").mkdirs();
        return root;
    }

    private static String displayName(Context context, Uri uri) {
        try (Cursor cursor = context.getContentResolver().query(uri,
                new String[]{OpenableColumns.DISPLAY_NAME}, null, null, null)) {
            if (cursor != null && cursor.moveToFirst()) {
                String name = cursor.getString(0); if (name != null && !name.isBlank()) return name;
            }
        } catch (RuntimeException ignored) { }
        return "selected-gpu-driver.zip";
    }

    private static void extractSafely(Context context, Uri uri, File destination) throws IOException {
        String root = destination.getCanonicalPath() + File.separator;
        int entries = 0; long total = 0; boolean any = false;
        try (InputStream raw = context.getContentResolver().openInputStream(uri);
             ZipInputStream zip = raw == null ? null : new ZipInputStream(raw)) {
            if (zip == null) throw new IOException("Document provider did not open the ZIP");
            for (ZipEntry entry; (entry = zip.getNextEntry()) != null; zip.closeEntry()) {
                any = true;
                if (++entries > MAX_ENTRIES) throw new IOException("Driver ZIP has too many entries");
                String name = safeEntryName(entry.getName());
                File output = new File(destination, name);
                if (!output.getCanonicalPath().startsWith(root)) throw new IOException("Unsafe ZIP path: " + name);
                if (entry.isDirectory()) { if (!output.mkdirs() && !output.isDirectory()) throw new IOException("Cannot create ZIP directory"); continue; }
                if (entry.getSize() > MAX_ENTRY_BYTES) throw new IOException("ZIP entry is too large: " + name);
                File parent = output.getParentFile();
                if (!parent.mkdirs() && !parent.isDirectory()) throw new IOException("Cannot create ZIP directory");
                try (OutputStream file = new FileOutputStream(output)) {
                    byte[] buffer = new byte[64 * 1024]; long entryBytes = 0;
                    for (int read; (read = zip.read(buffer)) != -1;) {
                        entryBytes += read; total += read;
                        if (entryBytes > MAX_ENTRY_BYTES || total > MAX_TOTAL_BYTES) throw new IOException("Driver ZIP expands beyond safety limit");
                        file.write(buffer, 0, read);
                    }
                }
            }
        }
        if (!any) throw new IOException("Driver ZIP is empty or invalid");
    }

    static String safeEntryName(String name) throws IOException {
        if (name == null) throw new IOException("ZIP entry has no name");
        String normalized = name.replace('\\', '/');
        while (normalized.endsWith("/")) normalized = normalized.substring(0, normalized.length() - 1);
        if (normalized.isEmpty() || normalized.startsWith("/") || normalized.matches("^[A-Za-z]:.*"))
            throw new IOException("Unsafe ZIP entry: " + name);
        for (String component : normalized.split("/"))
            if (component.isEmpty() || component.equals(".") || component.equals("..")) throw new IOException("Unsafe ZIP entry: " + name);
        return normalized;
    }

    static File findSupportedDriver(File directory) throws IOException {
        java.util.List<File> candidates = new java.util.ArrayList<>();
        collectDriverCandidates(directory, candidates);
        candidates.sort((left, right) -> Integer.compare(driverScore(right), driverScore(left)));
        IOException rejection = null;
        for (File candidate : candidates) {
            try { validateArm64Elf(candidate); return candidate; }
            catch (IOException error) { rejection = error; }
        }
        if (rejection != null) throw new IOException("Vulkan libraries were found, but none target Android ARM64. "
            + rejection.getMessage(), rejection);
        return null;
    }
    private static void validateArm64Elf(File file) throws IOException {
        byte[] header = new byte[20]; int offset = 0;
        try (InputStream input = new FileInputStream(file)) {
            while (offset < header.length) {
                int read = input.read(header, offset, header.length - offset);
                if (read < 0) break;
                offset += read;
            }
        }
        boolean elf = offset == header.length && header[0] == 0x7f && header[1] == 'E'
            && header[2] == 'L' && header[3] == 'F';
        boolean elf64 = elf && header[4] == 2;
        boolean littleEndian = elf64 && header[5] == 1;
        int machine = littleEndian ? (header[18] & 0xff) | ((header[19] & 0xff) << 8) : -1;
        if (!elf) throw new IOException(file.getName() + " is not an ELF shared library");
        if (!elf64) throw new IOException(file.getName() + " is not a 64-bit driver");
        if (!littleEndian || machine != 183)
            throw new IOException(file.getName() + " is not an ARM64 driver (ELF machine " + machine + ")");
    }
    private static void collectDriverCandidates(File directory, java.util.List<File> found) {
        File[] children = directory.listFiles(); if (children == null) return;
        for (File child : children) {
            if (child.isDirectory()) collectDriverCandidates(child, found);
            else if (child.isFile() && supported(child.getName())) found.add(child);
        }
    }
    private static int driverScore(File file) {
        String path = file.getAbsolutePath().replace('\\', '/').toLowerCase(Locale.US);
        String name = file.getName().toLowerCase(Locale.US); int score = 0;
        if (path.contains("/" + ABI + "/")) score += 100;
        if (name.equals("libvulkan_freedreno.so")) score += 40;
        else if (name.equals("vulkan.adreno.so")) score += 35;
        else if (name.equals("vulkan.freedreno.so")) score += 30;
        else if (name.equals("libvulkan.so")) score += 20;
        if (path.contains("/aarch64/") || path.contains("/arm64/")) score += 15;
        if (path.contains("/x86") || path.contains("/armeabi-v7a/")) score -= 100;
        return score;
    }
    private static boolean supported(String name) {
        String lower = name.toLowerCase(Locale.US);
        if (!lower.endsWith(".so")) return false;
        for (String allowed : SONAMES) if (allowed.equalsIgnoreCase(name)) return true;
        return lower.contains("vulkan") || lower.contains("freedreno") || lower.contains("turnip");
    }
    private static void deleteRecursively(File file) {
        File[] children = file.listFiles(); if (children != null) for (File child : children) deleteRecursively(child);
        file.delete();
    }
}
